dist: xenial
sudo: false

language: node_js
node_js:
  - "12"

addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install firebase-tools
  - npm install

script:
  - npm run lint
  - ng build --prod

after_success:
  - firebase deploy --token 1/B2UstP6skz-kn406QGdM_KR7MuCLB8VbYONyeDtN-dA

notifications:
  email:
    recipients:
      - olelashaw@gmail.com
    on_failure: always
    on_success: always
